#!/usr/bin/php
<?php
	require_once __DIR__ . "/../application/UsernameGenerator.php";
	
	$usernamegenerator = new UsernameGenerator();
	
	var_dump($usernamegenerator->formatName("Samuel Thomas Elliott"));
	