#!/usr/bin/php
<?php
	date_default_timezone_set("Europe/London");
	require_once __DIR__ . "/../application/UsernameGenerator.php";
	
	$usernamegenerator = new UsernameGenerator();
	
	var_dump($usernamegenerator->createNew("Samuel Elliott", "2001-08-14"));
	